name: Generate UDI Labels

on:
  workflow_dispatch:
    inputs:
      product:
        description: "Produktname"
        required: true
      date:
        description: "Herstelldatum (YYMMDD)"
        required: true
      serial_start:
        description: "Start Seriennummer"
        required: true
      count:
        description: "Anzahl Etiketten"
        required: true
